steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-ar/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-ar/app:$COMMIT_SHA']
  

images:
  - 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-ar/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY