steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-cb/app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-cb/app:$COMMIT_SHA']

images:
  - 'us-central1-docker.pkg.dev/college-task-project/lohar-100925168-cb/app:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY # Ensure logging behavior is set


# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA', '.']
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA']
#   # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#   #   entrypoint: 'gcloud'
#   #   args: ['run', 'deploy', 'app-jashan-100946316', '--image', 'us-central1-docker.pkg.dev/eng-oven-435418-i5/jashan-100946316/app:$COMMIT_SHA', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']



# options:
#   logging: CLOUD_LOGGING_ONLY